name: workflow

on:
  push:
    branches:
      - main

jobs:
# ---------------- CI ----------------
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "Linting repository"
      - run: echo "Running unit tests"

# ---------------- BUILD + PUSH ----------------
  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image
        run: |
          docker build -t networksecurity .
          docker tag networksecurity:latest 963912059120.dkr.ecr.eu-north-1.amazonaws.com/networksecurity:latest
          docker push 963912059120.dkr.ecr.eu-north-1.amazonaws.com/networksecurity:latest

# ---------------- DEPLOY ----------------
  continuous-deployment:
    name: Continuous Deployment
    needs: build-and-push-ecr-image
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

            - name: Restart container
        run: |
          set +e

          docker stop networksecurity
          docker rm networksecurity

          set -e

          docker pull 963912059120.dkr.ecr.eu-north-1.amazonaws.com/networksecurity:latest

          docker run -d \
            --restart unless-stopped \
            --name networksecurity \
            -p 8000:8000 \
            963912059120.dkr.ecr.eu-north-1.amazonaws.com/networksecurity:latest


      - name: Cleanup
        run: docker system prune -af
